### ISSUE TITLE
Authenticating and logging in users

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/ecf2#1]
The application will have several kinds of users, all of whom need to be able to log in securely.

## Current situation in ECF1

ECF1 does this using a magic link system:

1. person goes to [the landing page](https://manage-training-for-early-career-teachers.education.gov.uk/) and clicks 'Sign in'
2. they are prompted to enter an email address
3. if the email address exists a token is generated and saved on the user record
4. the token is also embedded in a link which is emailed to the person 
5. the person receives the email and clicks the link
6. the token in the link is compared with the one in the user record, and if they match the person is logged in [and appropriately redirected](https://github.com/DFE-Digital/early-careers-framework/blob/main/app/forms/choose_role_form.rb#L26)

The authentication is handled by [Devise](https://github.com/heartcombo/devise), a large complex gem that supports several authentication strategies, but we [had to add custom code to make it work how we want](https://github.com/DFE-Digital/early-careers-framework/blob/main/lib/devise/strategies/passwordless_authenticatable.rb).

## How we want it to work in ECF2

Some further investigation is required to confirm these assumptions, but in ECF2 we want two options available for logging in:

### DfE Sign-in

Using email addresses causes many problems. Between Jan 1st and 19th March 2024 there were 198 helpdesk issues raised around school admins logging in. [These include](https://educationgovuk.sharepoint.com.mcas.ms/:p:/r/sites/TeacherServices/_layouts/15/Doc.aspx?sourcedoc=%7BA8D2E161-C0C6-472F-9B8F-E8A98DF8F42C%7D&file=Support%20tickets%20analysis.pptx&action=edit&mobileredirect=true) (note the term SIT isn't accurate, we now call them school administrators or school admins):

> * SIT has left school and new SIT is trying to log in​ and asking for help​
> * No SIT registered at school and trying to add them to the school for the first time​​
> * Teacher is trying to log in and has contacted us as they get stuck in a loop - we advise them who the SIT is and advise them if it needs to be changed to contact us or nominate a new one through the service

In addition to email-based login, admins at schools are likely to already be using [DfE Sign-in](https://services.signin.education.gov.uk/). Once set up this application will appear in the list of available services and login will happen in DfE Sign-in, we'll only need to hold minimal information (if any?) about the person in the database.

### Magic link or one time passwords (OTP)

Not all our users will have access to DfE Sign-in. Some schools won't have registered for it and users from Lead Providers, Delivery Partners and Appropriate Bodies probably aren't eligible. We'll have to provide some kind of fallback, and using magic links or a OTP is sensible.

An advantage of OTP over magic links is that some people are likely to receive emails on a device other than the one they're using to access the service (i.e., trying to log in on laptop, emails received on phone).

## Tasks

* [ ] Integrate with DfE Sign-in
    * [x] find out who DfE Sign-in is available for. We know schools can access it, but can all ABs/DP/LPs etc]? @claire-hughez's comment below provides more information 
    * [ ] work out the best approach for doing this as there are several in use across Teacher Services:
      * use a [openid_connect](https://github.com/nov/openid_connect) and [the original reference implementation for inspiration](https://github.com/DFE-Digital/login.dfe.examples.rails/commit/fcc291d7c054293c4042c3bdb66d77ea26a9f35f)
      * use an pre-made gem like [OmniAuth](https://github.com/omniauth/omniauth_openid_connect)
  * [ ] implement DfE Sign-in integration
* [x] #109
* [ ] Make sure both approaches work consistently and don't interfere with each other
* [ ] Consider implementation for #125 
* [x] #138 
* [x] #24 
* [x] #85

**Comment by claire-hughez** [comment]
I wonder how DFE Sign in authenticates their first user when they don't have approvers. They can't authenticate against itself!

It would be good to find out more on if there are any schools not using DFE sign in. I'm pretty sure most will be, and it's relatively easy to get set up, but that's an assumption to test.

We also have ITT providers using DFE Sign in, so I'd challenge Lead providers or Appropriate bodies not being able to use it. Again, understanding that better and what other services use to authenticate them might be helpful.

I just checked the [ESFA service they have to use for funding purposes and that uses DFE Sign in](https://skillsfunding.service.gov.uk/).... another good reason to align it by using DFE Sign in for lead providers at least.

Both Apply for teacher training and Register trainee teachers use a fallback for DFE sign in, but this is only when it is down and not working. We'd probably want something similar and it seems like it might be needed for the edge cases where a user couldn't use DFE Sign In.

Finally, checked how you can search for organisations, and there's a few identifiers here beyond URNs. ![Screenshot 2024-06-11 at 20 08 18](https://github.com/DFE-Digital/ecf2/assets/93539621/1b9ad9b7-4f9b-4538-b440-88840347e254)

Feel like we could check all the lead providers and appropriate bodies against this fairly easily. We could even ask the team for a CSV of all the orgs on there to check GIAS data against too.

**Comment by peteryates** [comment]
> I wonder how DFE Sign in authenticates their first user when they don't have approvers. They can't authenticate against itself!

So I think you can sign up for a DfE Sign-in account without being attached to a school, then once you're logged in there's a 'Request access to an organisation' flow. My hunch is that if there are no approvers set up for that org, someone at DfE Sign-in's end confirms who you are (maybe by sending an email to the GIAS contact address!)

**Comment by peteryates** [comment]
@claire-hughez do you know how it would work if we used DfE Sign-in for our admin accounts. They wouldn't be attached to an _organisation_. Or would we need to fall back to magic links for them?

**Comment by claire-hughez** [comment]
@peteryates We can use Dfe Sign In for support. Register trainees and Apply for ITT both do.
![Screenshot 2024-07-24 at 19 32 36](https://github.com/user-attachments/assets/a35edc20-e990-4b21-b373-86b982e23442)

I just don't have anything under 'my organisations', just 'my services'.

**Comment by peteryates** [comment]
It looks like the original theory that we'll need both [was confirmed by this comment](https://github.com/DFE-Digital/ecf2/discussions/43#discussioncomment-10276331) so probably worth doing a little experimentation with a nicer way of doing email login.

**Comment by peteryates** [comment]
Having done a bit more investigation with @tonyheadford we think that it's sensible to use [omniauth](https://github.com/omniauth) because:

* it will allow us to use [omniauth_openid_connect](https://github.com/omniauth/omniauth_openid_connect) for DfE Sign-in
* it _should_ allow us to use something like [omniauth-identity](https://github.com/omniauth/omniauth-identity) for email/OTP style login
* it's already heavily used across @DFE-Digital

**Comment by peteryates** [comment]
We might also want to take a bit of inspiration (or even perhaps integrate) [Passwordless](https://github.com/mikker/passwordless) with omniauth when it comes to our non-DfE Sign-in auth.

**Comment by peteryates** [comment]
@steventux, @tonyheadford and I have just had a chat about sign-in and auth and here are some thoughts.


## Make school use DfE sign-in

DfE sign-in provides us with a reliable list of associations between users and schools. If we attempted to store this locally we'd run the risk of our mapping not matching, which could lead to confusion.

## Non-DfE users to have the option of DfE sign-in or one time password (OTP)

 As @claire-hughez says in [this comment](https://github.com/DFE-Digital/ecf2/issues/51#issuecomment-2283457292), lead providers, appropriate bodies and delivery partner users aren't cleanly mapped to the right organisation types.

We'll need to store a list of users for each organisation. The user record might only need to contain an email address (minimally) or we could extend it to hold their name too.

Having a list of email addresses that can access an organisation give us flexibility over how they log in. When

* they log in via DfE sign-in their email address is provided as part of the payload so we can match it to their user record and get the right organisation. If they have more than one organisation we'll probably have to allow them to pick the one they want
* they log in via a OTP we know they have access to the email address we sent the code to, so can match it to their user account with confidence. Again, if they have more than one organisation we'll have to allow them to pick the one they want

##  DfE staff

DfE staff (support, finance, etc) don't need access to specific organisations so we don't need to worry about any matching. We can hold a simple user record that contains an email address, name and 'level' of access and they can log in either by DfE sign-in or OTP.

**Comment by peteryates** [comment]
Following on from the above, @tonyheadford, @claire-hughez and I had a chat and we came to the following consensus:

1. it's more flexible to have one users table and link it via a join table to the schools, appropriate bodies and lead providers where necessary
2. we want one source of truth for school admins over which establishments they have access to; that is DfE Sign-in. We receive the school's URN in the OIDC payload and we can check for all the URNs they have access to [with the DfE Sign-in API](https://github.com/DFE-Digital/login.dfe.public-api?tab=readme-ov-file#get-organisations-for-user)
3. the ECF2 app will keep store the roles/access for non-school admin users, including their associations with organisations (ABs, LPs, maybe DPs) and, for DfE admins, it will hold their access level. This means we need to verify who they are by checking they have:
    * access to a DfE Sign-in account with the corresponding email address
    * access to the email address's inbox for OTP 

![image](https://github.com/user-attachments/assets/14c9b488-33ab-4c42-b352-8a2f938ba4d9)

**Comment by tonyheadford** [comment]
@claire-hughez @peteryates I have started building this out in a basic form, there isn't a ticket for it as far as I can see other than this - should this be the "ticket" on the sprint board?
