### ISSUE TITLE
Build the data migration process

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/ecf2#155]
The need for us to migrate data is [covered in data migration the wiki page](/DFE-Digital/ecf2/wiki/Data-migration).

We will be choosing the data we need from ECF1, extracting it, transforming it and importing it to ECF2.

## Tasks

* [ ] identify what data we need from ECF1
* [ ] map the ECF1 data to the new ECF2 schema
* [ ] build the actual migration framework:
    * [ ] connect the ECF2 migration env app to the ECF1 migration env database (dependant on #7)
    * [ ] create a proof of concept migration for an 'easy' table like Lead Providers
    * [ ] then tackle the more complex area (participants, induction records, finance, etc)
 * [ ] build a dashboard or report that tells us how well the migration went, use [NPQ's for inspiration](/DFE-Digital/npq-registration/pull/1077) for inspiration. Ideally this should give us an idea of what percentage of records were cleanly imported

## Outcomes

* a migration environment that's connect to ECF1's migration environment
* a process that pulls data from ECF1 and saves it in ECF2
* some kind of output that tells us how successful the migration was

## Follow up tasks

* iterate and improve the migration process aiming for a high a match rate as possible
