### ISSUE TITLE
Add the required tables, fields and appropriate model validations

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/ecf2#204]
The data we will receive from appropriate bodies via CSV uploads and what it relates to is:

* the appropriate body:
    * `Establishment ID`
* the ECT:
    * `TRN`
    * `Surname`
    * `First Name`
    * `Date of Birth`
    * `Induction Outcome`
* an induction period:
    * `Induction Programme Type`
    * `Induction Period Start Date`
    * `Induction Period End Date`
    * `Induction Period Number Of Terms`

We intend to record data in the following process:

1. we add incoming teacher/induction data to a staging area where it's given a `pending` status
2. a background job is triggered for each row, it checks the eligibility of the teacher against the TRS API. We probably want to check for duplicates too (i.e. another row for the teacher with the same start date). The result should be one of the following:
    * **eligible** - we persist the data to the main schema and delete the staging row
    * **ineligible** - we leave the staging row so the AB can see that something didn't go to plan and hopefully give a constructive reason why it didn't. We might want to let them tweak the data in the staging area to fix a typo or something before it's resubmitted
    * **failure** - the API couldn't be reached, there was a bug, etc. Add a message/event saying what happened and schedule a retry.

## Tasks

* [x] create a _staging_ table (come up with a better name) that holds the submitted data specified above
* [x] add the fields to the database that will hold the persisted data:
    * [x] `appropriate_bodies.local_authority_code`
    * [x] `appropriate_bodies.establishment_number` (these two combined make the `EstablishmentID`)
    * [x] `teachers.trn`
    * [x] ~~`teachers.induction_outcome` (think about this first!)~~
    * [x] `induction_periods.programme_type` (will need an enum)
    * [x] `induction_periods.number_of_terms`

We won't persist `Surname`, `Firstname` or `Date of Birth`

**Comment by emily-prudence-dfe** [comment]
A thought on the duplicates:

We know anecdotally that schools typically register ECTs for training earlier than the ECT is registered for induction by their AB (AB deadlines to register new induction starts are 6-8 weeks into term, whereas ECTs and schools want training to start earlier than this) but not always.

While it won't be a problem initially (assuming induction writes to the ECF 2.0 data model before any actual ECF data is migrated into it) we should prepare for the very likely scenario that:

* An AB registers an induction start
* The ECT is already registered for training, so they already have a record of them in the ECF database
* The ECT doesn't have any induction history

In this case, we wouldn't want to write the ECT's details to the database (because we'd create a duplicate record) but we would want to create a new induction history for them.

However, the inverse can be true too; there's no set order that training & induction registration have to happen (until we properly join up the journeys) so we need to prepare for the scenario where an ECT is new to ECF when induction registration happens, then if/when they're registered for training we link it to their existing induction record rather than creating a new one.

**Comment by peteryates** [comment]
I believe we have mitigated for this in the data model by separating training and induction data - they're stored together in ECF1.

TRN, is a unique attribute of the `teachers` table and will prevent duplicates. The potential clash is if/when we get different periods of induction/training from different sources and they clash, *but* we will include validation to ensure they can't overlap.

I think this will make it a data importing/cleansing problem rather than a duplicates problem. Happy to discuss this more though.

**Comment by peteryates** [comment]
Ah yeah good point. We can have a proper think about that, I'm sure there are all kinds of other situations like that too!

**Comment by gracecbrennan** [comment]
This is close to being ready for review.
