### ISSUE TITLE
User roles

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/ecf2#241]
Several different kinds of people will use the service, including:

* School admins (formerly known as SITs)
* DfE staff (admin, finance)
* Appropriate body users

When they log in we want to ensure they are directed to the right place and can only see what they're meant to see.

## Tasks

* [ ] Add separate layouts per user type (school admins, dfe admins, appropriate bodies)
* [ ] Ensure people who sign in with a particular role are directed to the right area and can only see that area
* [ ] We need to be able to grant users roles - discuss this before implementing!
* [ ] Extend the personas so they cover the different roles
* [ ] Add a secondary navigation menu so DfE admins can drill into specific areas

**Comment by steventux** [comment]
## Users & roles
 
#### What questions do we ask of the authorisation service?

- What type of user is this?
- Can this user access data for this AB or School?
- Which ABs or Schools does this user have access to?
- Which users have access to this AB or School?
- Is this an admin or super admin or finance user?
- What are all the roles this user has?
- What are all the possible user roles?

#### Additional more general questions

- How do DfE staff authenticate?
- DfE Sign In usually still requires that we persist some user data, these will typically be school admin users. Do school admins have varying levels of access?

#### Technical notes

We will probably have several user types, we may eventually have several organisation types.
Regardless of this we should have one common service-like authorisation object that we can ask the above questions.

**Comment by claire-hughez** [comment]
Get something out for people to talk about that is just a draft.

**Comment by claire-hughez** [comment]
This morning will try and get a draft out

**Comment by claire-hughez** [comment]
Pushed up draft, thought about ways to authorise users. Up for discussion, trying to lock down admin controller as proof of concept. Steve will push up those commits soon.

**Comment by gracecbrennan** [comment]
PR is open. 

Steve is going to take a look at one of the last parts for when a user logs in and we find out who they are.
