### ISSUE TITLE
Stub some TRS API calls

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/ecf2#289]
These API endpoints don't exist in the TRS API yet but they will (hopefully) be in place by the end of November.

We need to be able to inform TRS:

* when an ECT has started their induction, by sending their
    * start date
    * status (possibly - it might always start as `started` or something in which case this is pointless)
* when an ECT has completed their induction, by sending their
    * completion date
    * status (e.g., `passed`, `failed`)

## Tasks

* [ ] stub these API methods in `TRS::APIClient` (just log a message for now)
* [ ] allow them to be called from `TRS::Teacher`
   ```ruby
    teacher = TRS::Teacher.new(trn: '1234567')
    teacher.begin_induction!(start_date: '2023-01-01')
    # or
    teacher.induction_complete!(completion_date: '2023-01-01', status: 'failed')
    ```
* [ ] add the sample calls to the relevant bits of the app
