### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/ecf2#313]
We now have the idea of users and roles in the app #241

The above PR added a user management UI that is focussed around the user. A user is selected and then their roles are configured:

| Select role type | Assign roles |
| ------------ | --------------- |
| ![Screenshot from 2024-09-23 13-32-46](https://github.com/user-attachments/assets/64dc8efe-2c3a-4916-9ff3-6bc7598af581)| ![Screenshot from 2024-09-23 13-32-53](https://github.com/user-attachments/assets/d3ad50f4-f954-4490-a786-917d05c025e5) |

This approach is ok for now but:

* it won't scale when we have hundreds of establishments
* it's unlikely that we want to configure this at the user level

It's probably going to make far more sense to admins to find the organisation they want to add someone to, click on the 'Users' link in the nav and then add the user. This means we don't need to ask them for the type of establishment or role (org).

## Tasks

* [ ] Add the user management screens for lead providers
* [ ] Add the user management screens for delivery partners
* [ ] Add the user management screens for appropriate bodies
* [ ] Add the user management screens for DfE staff
