### ISSUE TITLE
"Claim" an ECT (start an induction period)

### ISSUE THREAD

**Issue by emily-prudence-dfe** [DFE-Digital/ecf2#328]

**Comment by peteryates** [comment]
I think we have this already in #265.

**Comment by joe-harrison-dfe** [comment]
Tasks: 

- [x] Collect TRN and DoB
- [ ] Match TRN and DoB with a TRS Record
- [ ] Match TRN and DoB with a CPD Record
- [ ] Check teacher is eligible to start an induction
- [ ] Check QTS status
- [ ] Check induction completion
- [ ] Check induction exemption
- [ ] Check alerts and prohibitions 
- [ ] Checking that the teacher can be claimed by the AB
- [ ] Check for open induction periods with a different AB
- [ ] Check for open induction periods with the AB attempting to claim the ECT
- [ ] Prompting ABs to check the teacher's record
- [ ] Collecting data bout the teacher's induction
- [ ] Creating a new teacher record, if one doesn't exist in ECF
- [ ] Creating a new induction period
- [ ] Updating TRS, if the teacher is starting a new induction

**Comment by joe-harrison-dfe** [comment]
Content Tasks:
- [ ] Check details page - #729 
- [ ] Find an ECT record - #730 
- [ ] Tell us about ECT's induction page - #731 
- [ ] Success teacher claimed page - #732 
- [ ] **Claim unhappy paths**
- [ ] QTS not awarded - #479 
- [ ] Can't find ECT - 
- [ ] Prohibited from teaching - #742 
- [ ] Non-prohibition alerts - #741 
- [ ] Teacher already completed induction - #517 
- [ ] Teacher has open induction period with another AB - #728 
- [ ] Teacher has open induction period with the claiming AB - #728 
- [ ] Teacher is exempt from completing induction - #517
