### ISSUE TITLE
Record an induction outcome

### ISSUE THREAD

**Issue by emily-prudence-dfe** [DFE-Digital/ecf2#330]

**Comment by joe-harrison-dfe** [comment]
Tasks: 

- [x] Collect data on an induction stop - stop date, number of terms and outcome
- [ ] Validating the number of terms 
- [ ] Closing an induction period
- [ ] Updating TRS with the outcome & completion date
- [ ] Reminding ABs of the information they need to provide ECTs in the case of a Fail outcome

**Comment by joe-harrison-dfe** [comment]
Content Tasks:

- [x] Record an induction page
- [ ] **Outcome content**:
- [ ] Pass page
- [ ] Fail Page
- [ ] Same content for term validation and end date as release
- [ ] Induction complete page
