### ISSUE TITLE
View ECTs and induction history

### ISSUE THREAD

**Issue by emily-prudence-dfe** [DFE-Digital/ecf2#332]

**Comment by joe-harrison-dfe** [comment]
Content Tasks:

- [ ] List of ECT records page
- [ ] Individual ECT record page 
- [ ] Extension content on view a record page 
- [ ] Buttons to link to different journeys
