### ISSUE TITLE
Change induction programme

### ISSUE THREAD

**Issue by emily-prudence-dfe** [DFE-Digital/ecf2#333]

**Comment by joe-harrison-dfe** [comment]
Tasks: 

- [x] Collect data about an induction stop - including stop date, number of terms and new induction programme type.
- [x] Validating the number of terms
- [x] Closing an induction period
