### ISSUE TITLE
Service rules

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/ecf2#4]
ECF is a *really complicated area*. [The policy](https://github.com/DFE-Digital/ecf2/blob/main/documentation/policy/induction-for-early-career-teachers.adoc) is complex and [the contracts](https://github.com/DFE-Digital/ecf2/blob/main/documentation/providers/ecf-call-off-contract-2023-2024-redacted/contract.adoc) are complex. The service needs to ensure both sets of needs are met, along with taking care of requirements made by DfE and CPD, therefore it is _complex_.

We've tried to create various all-encompassing documents and diagrams to show this in the past but ultimately failed. Trying to document 'the business rules' all in one go spirals into an unmanageable tome. Trying to represent it as a flowchart doesn't really work either because ECF is a (minimum) two year process and there are so many combinations and routes that diagrams soon become unmanageable.

The idea of service rules falls somewhere between.

Essentially they are:

* **split by user type**
   We know our users and what they need to do; dividing the rules by user makes most sense
* **itemised by interaction**
   Each rule should describe an action that someone takes. For example, registering an ECT. We'd expect the rule would tell us what data we need to capture, how we would validate it, when we can do it, etc
* **briefly described in plain English with any conditions, states and processes listed**
   These should be small, easy to read and maintain
* **supported by and cross-referenced (via hyperlinks) with at least one of:**
   * the policy
   * the contracts
   * DFE/CPD needs
   * user research

If we can't find justification in those places for the rule to exist, we should question it.

@mason-emily has already done a fantastic job on drafting them in a Word document, that will be imported to form the starting off point.

## Tasks

* [x] Import the service rules from Word (use Pandoc)
* [x] Make sure the source document is marked as no longer being the source of truth
* [x] Ensure the links work properly and fix any formatting
* [ ] Create a static documentation site that publishes them on GitHub Pages (Being done in #40)
