### ISSUE TITLE
Set up a frontend testing framework

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/ecf2#47]
At some point we'll end up with a few pages that have custom JavaScript. This is most likely going to be pages where we allow [autocompletion](https://github.com/DFE-Digital/dfe-autocomplete) or if we ever need to show a cookie banner (hopefully not!) so we can test dismissing it.

The vast majority of our tests, and no end-to-end type ones, should need to run in the browser.

ECF1 and NPQ both use [Selenium](https://github.com/SeleniumHQ/selenium) but since they were written [Playwright](https://github.com/microsoft/playwright) has emerged and it has a nice clean [Ruby client](https://github.com/YusukeIwaki/playwright-ruby-client).

## Tasks

* [x] Create a placeholder page with a small amount of JavaScript functionality to test with
* [x] Investigate integrating Playwright with RSpec and writing some tests that ensure the JavaScript works properly
* [x] Document the process of running and debugging the tests, maybe on a new 'Testing' page in [the wiki](https://github.com/DFE-Digital/ecf2/wiki) or in a file linked from the README.

**Comment by gracecbrennan** [comment]
Lorenzo is investigating Playwright to see if this is appropriate candidate for this project.

**Comment by gracecbrennan** [comment]
Halfway on this ticket to investigate the new end-to-end testing framework making good progress.

**Comment by mason-emily** [comment]
About to finish this investigation. @peteryates @tonyheadford @ltello to spend some time reviewing today

**Comment by gracecbrennan** [comment]
@peteryates has reviewed and is going to share comments on here. 

@tonyheadford to take a look today.

**Comment by gracecbrennan** [comment]
@pete to review third option in more detail today

**Comment by gracecbrennan** [comment]
Check with @peteryates when he's back if he had a chance to review thiurd option

**Comment by ltello** [comment]
I have found a way to install Playwright without Capybara (third option).
Still checking different scenarios but the approach works very well so far. 
Test suite runs times faster under this method.

Next step:
- Final twicks to the way we start playwright and the rails server on every test suite run. 
- add a Testing page in the Wiki to document how devs can run the test suite.

**Comment by peteryates** [comment]
@ltello I took some of your code and adjusted it to work with the Capybara, just to see how minimal a setup we can have. 

Happy to go with any so long as it's easy and intuitive, but #161 looks decent to me.

**Comment by claire-hughez** [comment]
Discussing an option to choose still. Today a decision will be made and this can be merged, based off Option 1.

**Comment by claire-hughez** [comment]
Wait until Pete is back to review this.

**Comment by claire-hughez** [comment]
Discussion and vote needed for testing today.

**Comment by peteryates** [comment]
I like this. Initially #180 was my preferred approach *but* I'm willing to give #183 a try. The [playwright documentation](https://playwright-ruby-client.vercel.app/docs/api/page) is really comprehensive and it seems to run nice and quick.

I think #180 is the safest bet, we know Rack and Capybara _really well_. If we opt for #183 I think we should evaluate the choice after we've built our first couple of features and see how we feel as a team.

Thoughts @steventux, @tonyheadford?

**Comment by ltello** [comment]
[Issue](https://github.com/DFE-Digital/ecf2/issues/175) created to remove the sample code/specs once devs are familiar with Playwright and these samples are not needed anymore
