### ISSUE TITLE
Testing pipeline 🔧 

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/ecf2#48]
Every time we push code to a branch or merge a branch to `main` we want to ensure it meets some standards, namely:

* the code doesn't contain any syntax errors or other warnings from Rubocop
* the tests pass
* the pages we've built are accessible
* the changes don't introduce any security risks

Each of the above steps will eventually form a deployment pipeline, here's ECF1's for reference:

![image](https://github.com/user-attachments/assets/9ea4ce1d-3e16-44c4-a4c7-f8c1c720494f)

For now though we just want them to run, the pipeline will be added later when we begin adding the actual infrastructure.

## Tasks

Add actions that:

* [x] run RSpec (no matrix or parallelisation for now)
* [x] lint Ruby
* [x] lint JavaScript
* [x] lint CSS
* [x] run the [Brakeman vulnerability scanner](https://brakemanscanner.org/) or [Bearer](https://github.com/Bearer/bearer) scan
* [ ] run accessibility checks, [there's an example here on doing it with Playwright](https://playwright.dev/docs/accessibility-testing) (or alternatively we can [run axe through selenium](https://github.com/dequelabs/axe-core-gems))

**Comment by gracecbrennan** [comment]
Steve is half-way through this and has a draft pull-request. This is going well and expects to be wrapped up today.
