### ISSUE TITLE
Importing school data 🏫 

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/ecf2#50]
While the final data model isn't yet finalised we **know** we'll need a table containing school data from GIAS.

Essentially, this time around, we intend on having two 'school' models:

* `School` - our representation of a school within the system
* `GIAS::School` - a direct import from GIAS that uses `urn` as primary key

The separation will allow us to deal with things like [the academisation of schools](https://www.gov.uk/guidance/convert-to-an-academy-information-for-schools) by simpliy switching the URN on the `School`, rather than having to migrate all the attached stuff over to a new school record. We'll just concentrate on `GIAS::School` for now though.

## Tasks

* [x] Work out which columns we need - I suspect we can start with `urn`, `name`, `section_41_approved`
* [x] Create a minimal `GIAS::School` model with the identified fields
* [ ] Create a task that pulls GIAS data and imports it. As we're likely to be using DfE Sign-in this time around let's try starting off with this [dfe-data](https://github.com/DFE-Digital/gias-data) export first, it makes the process much easier by taking care of the CSV processing and gives a nice JSON file we can just pull in. We only need open schools so ignore the closed ones.
* [ ] Add a service class responsible for doing the pull/import
* [ ] Add a rake task that performs the import

## Bonus stretch task

* [ ] #337
    * Predecssor
    * Successor
    * Predecessor - merged
    * Successor - merged
    * Successor - amalgamated
    * Predecessor - amalgamated
    * Merged
    * Plus quite a few more... 🤷🏽 

## Future notes

At some point in the future we're likely to want the email addresses/contact info from the GIAS API. We may want to create a slightly different import to pull that info.

**Comment by tonyheadford** [comment]
I've done a bunch of this, with discussions with @peteryates but still ongoing

**Comment by tonyheadford** [comment]
I've built quite a bit more of this and there are a couple of things worth noting:
* We found the JSON approach with that amount of data _much_ slower than reading and processing the GIAS CSV so have gone with the CSV
* I've used a different approach to the service class based upon the principle of a class with related public service methods instead of the one class per service with a `call` method and associated magic to make it work as a class method as used in ECF v1.
* The import and basic update from GIAS is there, the handling of closures/mergers/splits etc has not been done as yet

**Comment by claire-hughez** [comment]
Working on other ticket on testing, will pick this up if there's time.

**Comment by claire-hughez** [comment]
Tony and Lorenzo to catch up on this. Sticking with CSV files.

**Comment by claire-hughez** [comment]
Pete and Lorenzo to catch up

**Comment by ltello** [comment]
In case we need it to break this into smaller tickets, these are the types of links coming from GIAS:
`{"Predecessor - merged"=>186,
 "Predecessor"=>12595,
 "Sixth Form Centre Link"=>48,
 "Successor - amalgamated"=>9,
 "Successor - merged"=>23,
 "Successor"=>509,
 "Predecessor - amalgamated"=>68,
 "Result of Amalgamation"=>34,
 "Merged - expansion in school capacity and changer in age range"=>3,
 "Expansion"=>2,
 "Other"=>4,
 "Merged - expansion of school capacity"=>3,
 "Closure"=>2,
 "Merged - change in age range"=>4,
 "Sixth Form Centre School"=>47,
 "Successor - Split School"=>43,
 "Predecessor - Split School"=>42}`

**Comment by mason-emily** [comment]
Ticket #188 is going to be worked on first before this can be picked back up

**Comment by gracecbrennan** [comment]
Ticket is ongoing.

**Comment by claire-hughez** [comment]
Lorenzo is on ECF1 today.

**Comment by claire-hughez** [comment]
Lorenzo is back on this ticket today, most of the work is sorted on ECF1.

**Comment by claire-hughez** [comment]
Issue on ECF1 is still ongoing, so working on this when he can.

**Comment by claire-hughez** [comment]
Adding validation and tests to the PR. Still discussing ECF1 issue.

**Comment by gracecbrennan** [comment]
PR is ready for review 

@peteryates / @tonyheadford to take a look. 

Is looking at the task of importing schools from GIAS (2nd PR from this ticket)

**Comment by gracecbrennan** [comment]
Yesterday made progress on second PR.

**Comment by claire-hughez** [comment]
Hopefully this will be done by end of today or tomorrow, depends on ECF1 needs. 

Tony will review first PR today.

**Comment by gracecbrennan** [comment]
PR has been reviewed with team. This can be shared for review.

**Comment by gracecbrennan** [comment]
The last PR for this ticket is ready for review if @tonyheadford / @peteryates can review?

Is going to check logic with Claire/Emily

**Comment by gracecbrennan** [comment]
Discussion around how we determine if a school is from England or not - making a decision with @mason-emily on this.

**Comment by ltello** [comment]
Working with @mason-emily and finally we are determining the location of a school based on the `establishment type` (a field we already receive).
Logic implemented and PR merged.
