### ISSUE TITLE
Environments and deployment pipelines

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/ecf2#7]
ECF2 will follow the [continuous delivery model set out in DfE's technical guidance](https://technical-guidance.education.gov.uk/guides/continuous-delivery), we will follow the [pattern established in ECF1](https://github.com/DFE-Digital/early-careers-framework/blob/main/.github/workflows/deploy.yml) and the applications deployed on DfE's Azure space and follow the established conventions.

![image](https://github.com/DFE-Digital/ecf2/assets/128088/d4b09673-1fd3-4b5a-a765-da8192a34ced)

## Environments

We will need the following environments, both in Azure and Rails. *The names should match*, so `review`  apps run with the `review` Rails environment.

### Test subscription (`s189t01`)

* [x] review
* [x] staging

### Production subscription (`s189p01`)

* [x] migration (temporary, will be used while testing the importing of data from ECF1)
* [x] sandbox (maybe rename this to `lead_provider_sandbox` to make it clear what it's for)
* [x] production

### On every commit to a pull request

- [x] syntax is checked with [rubocop-govuk](https://github.com/alphagov/rubocop-govuk)
- [x] tests are run
- [x] security checks are run ([Brakeman](https://brakemanscanner.org/) or [Bearer](https://github.com/Bearer/bearer))
- [x] review app is deployed

The ECF1 pipelines also run smoke tests and API performance tests, but we won't be ready for those for a while. 

### When a pull requests are closed or merged

- [x] destroy the review app

### When pull requests are merged

- [x] all of the above steps
- [x] deploy to staging
- [x] deploy to sandbox/migration/production

## Approach

Like in ECF1, [build actions](https://github.com/DFE-Digital/early-careers-framework/tree/main/.github/actions) for bits we might want to reuse. This keeps things modular _and_ makes the actual flows [much shorter and easier to read](https://github.com/DFE-Digital/early-careers-framework/blob/main/.github/workflows/deploy.yml#L190).

We'll need help from @DFE-Digital/teacher-services-infrastructure with Azure keys for each environment.

**Comment by peteryates** [comment]
Having thought more about this I'd also like us to keep the root of the repo tidy and minimal. The infrastructure config _is_ config - let's put it (both `terraform` and `global_config`) under `config`?

**Comment by saliceti** [comment]
> Having thought more about this I'd also like us to keep the root of the repo tidy and minimal. The infrastructure config _is_ config - let's put it (both `terraform` and `global_config`) under `config`?

This makes sense. The inconvenients are this will deviate from the template so paths must be amended, and it will make it a bit more difficult to support. Also "config" is specific to rails.

**Comment by peteryates** [comment]
That's fair, appreciate it brings a support burden too. Maybe having `terraform` at the project root isn't so bad and we put `global_config` in that directory too?

**Comment by gracecbrennan** [comment]
Steve is progressing through Terrafrom set-up

**Comment by saliceti** [comment]
I suggest [generating fresh code from template](https://github.com/DFE-Digital/teacher-services-cloud/blob/main/documentation/onboard-service.md#generate-code) but tweak the azure naming in [the template](https://github.com/DFE-Digital/teacher-services-cloud/tree/main/templates/).
If it works, you can PR the template.

**Comment by mason-emily** [comment]
@tonyheadford looking at this today

**Comment by gracecbrennan** [comment]
Ongoing work with the infrastructure team. Steve is chatting with Colin on this at the moment and we should soon have our resources available to build out environments.

**Comment by gracecbrennan** [comment]
Colin was due to take a look at this yesterday but that hasn't happened just yet - Steve will chase up with Colin.

**Comment by gracecbrennan** [comment]
Colin has review draft pull request and he is continuing to create Azure elements we can't self-serve on.

**Comment by mason-emily** [comment]
Waiting on infrastructure team - Colin is keeping an eye on this

**Comment by steventux** [comment]
https://trello.com/c/72rf64KK is the Trello card for infra work on this.

**Comment by peteryates** [comment]
We can use [this action](https://github.com/DFE-Digital/teacher-pay-calculator/blob/main/.github/workflows/deploy.yml#L17) for building and pushing to the container registry.

**Comment by gracecbrennan** [comment]
Ticket is ongoing. Steve is doing a dry-run - will bring up test environment first and move onto prod etc.

**Comment by gracecbrennan** [comment]
Have got to a point of spinning up a review environment - this is currently timing out but Steve is going to look at this today.

**Comment by steventux** [comment]
We have a review app POC https://ec2-review-79-web.test.teacherservices.cloud/ 
Decided to break PRs down to each environment, the first (review env) PR is being checked by Colin.
Will follow with staging and other envs, these should be fairly trivial in comparison to initial setup.

**Comment by peteryates** [comment]
I think it was the 'Development' section on the right that was causing this issue to close. I _thought_ it'd close when all the development tasks were complete, not any of them 🙈  My fault, I've unlinked them now!

**Comment by mason-emily** [comment]
Staging environment is now up and running - waiting on code review on this 

Working on migration environment today with Colin.

**Comment by gracecbrennan** [comment]
Steve working on migration issue.

**Comment by gracecbrennan** [comment]
Sandbox and Production remaining that we hope to get done this week.

**Comment by gracecbrennan** [comment]
Migration and Sandbox solved. 

Pushing forward to production today!

**Comment by gracecbrennan** [comment]
All environments are now built!!! 

Waiting for entire deployment pipeline working correctly before we can move to done.

**Comment by steventux** [comment]
![Image](https://github.com/user-attachments/assets/c1733901-dac0-4485-9d9e-dbd46f526740)

Deploying to all environments
