### ISSUE TITLE
Emails ✉️ 

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/ecf2#8]
The application, like ECF1, will rely on email to notify users about various kinds of updates. It will use [GOV.UK Notify](https://www.notifications.service.gov.uk/) for all email sending.

## How it works in ECF1

ECF1's integration with Notify uses Notify's own templates as the master copy, and we refer to those templates [by uuid](https://github.com/DFE-Digital/early-careers-framework/blob/main/app/mailers/school_mailer.rb#L5) from within the app.

This is problematic because:

* changes to the personalisation data for each template need to be manually synchronised at the time of deployment
* we can't test the email contents
* when looking in Notify's UI it's hard to see which email templates are in use and which are deprecated
* we can't iterate/track email copy easy using git branches

It's advantages are:

* content designers can edit emails without needing to know git, so long as the edits don't change the personalisation options
* we can retrieve stats from Notify on email template usage

## How we should do it in ECF2

To overcome the problems above we should change the way we use Notify. Instead of having lots of templates we should have one that just contains a placeholder for the email body.

Then, we can build our emails [in the default Rails fashion](https://guides.rubyonrails.org/action_mailer_basics.html), [with tests](https://rspec.info/features/6-0/rspec-rails/mailer-specs/mailer-spec/), but still use Notify. We should still be able to obtain some stats from Notify about usage if we supply [the reference param](https://docs.notifications.service.gov.uk/ruby.html#reference-optional).

## Tasks

* [ ] make sure the suggested approach works ok and we can still format messages properly with basic Markdown.
* [ ] install and configure Notify
* [ ] add Notify keys to the appropriate environment vaults on Azure
* [ ] write some documentation so that devs know:
    * [ ] how to add new templates
    * [ ] how to generate dev keys for themselves
    * [ ] how to test email templates properly

**Comment by peteryates** [comment]
Note, this is how Apply's email setup works. You can see [a list of their email templates here](https://github.com/DFE-Digital/apply-for-teacher-training/tree/main/app/views/candidate_mailer).
